// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CodeGen is an autogenerated mock type for the CodeGen type
type CodeGen struct {
	mock.Mock
}

// GenerateCode provides a mock function with given fields: length
func (_m *CodeGen) GenerateCode(length int) (string, error) {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(length)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(length)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCodeGen creates a new instance of CodeGen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeGen(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeGen {
	mock := &CodeGen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
