// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	service "github.com/tranvantuan81/bookmark-management/internal/service"
)

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

// CheckHealth provides a mock function with no fields
func (_m *HealthCheck) CheckHealth() (service.Response, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 service.Response
	var r1 error
	if rf, ok := ret.Get(0).(func() (service.Response, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() service.Response); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(service.Response)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
